spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tars_admin
    username: tars_admin
    password: admin2447
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false

# JWT 설정
jwt:
  secret: devSecretKeyForJwtAuthenticationInDevelopmentEnvironment
  expirationMs: 3600000        # 액세스 토큰 만료 시간 (1시간)
  refreshExpirationMs: 86400000  # 리프레시 토큰 만료 시간 (24시간)

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 로깅 설정
logging:
  level:
    root: INFO
    com.tars: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 