spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tars_admin
    username: tars_admin
    password: admin2447
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 프로덕션에서는 validate 모드 사용
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# JWT 설정
jwt:
  secret: ${JWT_SECRET:tarsSecretKeyForJwtAuthenticationInProductionEnvironment}
  expirationMs: 3600000
  refreshExpirationMs: 86400000

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 로깅 설정
logging:
  level:
    root: WARN
    com.tars: INFO
  file:
    name: /var/log/tars/application.log 