spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tars_admin
    username: tars_admin
    password: admin2447
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${tars_jwt_secret}
  expirationMs: 3600000        # Access Token 만료시간 (1시간)
  refreshExpirationMs: 86400000  # Refresh Token 만료시간 (24시간)
